[package]
name = "servo_config"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[features]
uwp = []

[lib]
name = "servo_config"
path = "lib.rs"

[dependencies]
euclid = "0.20"
embedder_traits = { path = "../embedder_traits" }
getopts = "0.2.11"
lazy_static = "1"
log = "0.4"
num_cpus = "1.1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
servo_geometry = {path = "../geometry"}
servo_url = {path = "../url"}
url = "1.2"
servo_config_plugins = { path = "../config_plugins" }

[dev-dependencies]
env_logger = "0.6"
std_test_override = { path = "../std_test_override" }

[target.'cfg(not(any(target_os = "android", feature = "uwp")))'.dependencies]
dirs = "1.0"
